name: sadqah_jariyah_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  audioplayers: ^6.8.1
  flutter_launcher_icons: ^0.14.4
  adhan: ^2.0.0+1
  flutter_local_notifications: ^22.0.1
  geolocator: ^14.0.3
  permission_handler: ^12.0.3
  timezone: ^0.11.1
  intl: ^0.20.3
  url_launcher: ^6.3.2
  rename: ^3.1.0
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_mutqan.jpeg"
  adaptive_icon_background: "#0D4D43"
  adaptive_icon_foreground: "assets/images/logo_mutqan.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/azan12.mp3
    - assets/images/logo_mutqan.jpeg
